version: "3.8"
services:
  server:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    networks:
      - expzen_backend

  db:
    image: hypriot/rpi-mysql
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_DATABASE: expzendb
      MYSQL_USER: nikhilcodes
      MYSQL_PASSWORD: testtreasure321
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - db-data:/var/lib/mysql
    networks:
      - expzen_backend
volumes:
  db-data:

networks: 
  expzen_backend:
