server:
  port: 8000
  servlet:
    context-path: /api/

spring:
  security:
    user:
      name: doesntmatter
      password: doesntmatter

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:mysql://localhost:3306/creditzendb
    username: nikhilcodes
    password: shield3120

jwt:
  secret: gf768oyut7867v58b7rybpolkl09t6266g
